CREATE TABLE Client(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(200) NOT NULL CHECK(LENGTH(name)>=3 AND LENGTH(name)<=200)
);

CREATE TABLE Planet(
id VARCHAR(20) PRIMARY KEY,
name VARCHAR(500) NOT NULL
 );

CREATE TABLE Ticket(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
client_id BIGINT,
from_planet_id VARCHAR(20),
to_planet_id VARCHAR(20),
FOREIGN KEY (client_id) REFERENCES client (id),
FOREIGN KEY (from_planet_id) REFERENCES planet (id),
FOREIGN KEY (to_planet_id) REFERENCES planet (id)
);

